language: java
sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  email: false

before_script: cd examples

script: mvn clean verify  -Dmaven.test.redirectTestOutputToFile=true
